<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta name="generator" content="quarto-1.1.168">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>UCSD Political Science Math Camp - 3&nbsp; Data Wrangling</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1.6em;
  vertical-align: middle;
}
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { color: #008000; } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { color: #008000; font-weight: bold; } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */
</style>

<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./14_loops_simulations.html" rel="next">
<link href="./12_visualization.html" rel="prev">
<link href="./favicon.ico" rel="icon">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light"><script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit"
  }
}</script><style>html{ scroll-behavior: smooth; }</style>
<script type="application/json" class="js-hypothesis-config">
{
  "theme": "clean"
}
</script><script async="" src="https://hypothes.is/embed.js"></script><link rel="stylesheet" href="style.css">
</head>
<body class="nav-sidebar docked">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top"><nav class="quarto-secondary-nav" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }"><div class="container-fluid d-flex justify-content-between">
      <h1 class="quarto-secondary-nav-title"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Wrangling</span></h1>
      <button type="button" class="quarto-btn-toggle btn" aria-label="Show secondary navigation">
        <i class="bi bi-chevron-right"></i>
      </button>
    </div>
  </nav></header><!-- content --><div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse sidebar-navigation docked overflow-auto"><div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">UCSD Political Science Math Camp</a> 
        <div class="sidebar-tools-main">
    <a href="https://github.com/UCSDPoliMathCamp/MathCamp/" title="Source Code" class="sidebar-tool px-1"><i class="bi bi-github"></i></a>
  <a href="" class="quarto-reader-toggle sidebar-tool" onclick="window.quartoToggleReader(); return false;" title="Toggle reader mode">
  <div class="quarto-reader-toggle-btn">
  <i class="bi"></i>
  </div>
</a>
</div>
    </div>
      </div>
      <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
      </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">About this Booklet</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./00_warmup.html" class="sidebar-item-text sidebar-link">Warmup Questions</a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./01_prerequisites.html" class="sidebar-item-text sidebar-link">Prerequisites</a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">I Introduction to R</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./11_orientation.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">RStudio and Reading in Data</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./12_visualization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Visualization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./13_data_wrangling_cleaning.html" class="sidebar-item-text sidebar-link active"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Wrangling</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./14_loops_simulations.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Loops and Simulation</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./15_non-wysiwyg.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">LaTeX and Markdown</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">II Linear Algebra</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./21_vector_matrix.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Vector and Matrix</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./22_linear_systems.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Systems of Linear Equations</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./23_matrix_inverse.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Rank and Matrix Inverse</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">III Calculus</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./31_limits.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Limits</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./32_derivatives.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">10</span>&nbsp; <span class="chapter-title">Differential Calculus</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./33_optimization.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">11</span>&nbsp; <span class="chapter-title">Optimization</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./34_intergrals.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">12</span>&nbsp; <span class="chapter-title">Integral Calculus</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">IV Probability</a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">
<li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./41_probability.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">13</span>&nbsp; <span class="chapter-title">Probability Theory</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./42_distribution.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">14</span>&nbsp; <span class="chapter-title">Summarizing Distributions</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./43_statistics.html" class="sidebar-item-text sidebar-link"><span class="chapter-number">15</span>&nbsp; <span class="chapter-title">Learning from Data</span></a>
  </div>
</li>
      </ul>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./51_solutions-warmup.html" class="sidebar-item-text sidebar-link">Warmup Questions Solutions</a>
  </div>
</li>
    </ul>
</div>
</nav><!-- margin-sidebar --><div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active"><h2 id="toc-title">On this page</h2>
   
  <ul>
<li><a href="#clean-data" id="toc-clean-data" class="nav-link active" data-scroll-target="#clean-data"><span class="toc-section-number">3.1</span>  Clean Data</a></li>
  <li>
<a href="#cleaning-data-using-dplyr" id="toc-cleaning-data-using-dplyr" class="nav-link" data-scroll-target="#cleaning-data-using-dplyr"><span class="toc-section-number">3.2</span>  Cleaning Data Using dplyr</a>
  <ul>
<li><a href="#the-pipe-operator" id="toc-the-pipe-operator" class="nav-link" data-scroll-target="#the-pipe-operator">The Pipe Operator</a></li>
  </ul>
</li>
  <li>
<a href="#working-with-columns" id="toc-working-with-columns" class="nav-link" data-scroll-target="#working-with-columns"><span class="toc-section-number">3.3</span>  Working with Columns</a>
  <ul>
<li><a href="#select" id="toc-select" class="nav-link" data-scroll-target="#select">Select</a></li>
  <li><a href="#mutate" id="toc-mutate" class="nav-link" data-scroll-target="#mutate">Mutate</a></li>
  </ul>
</li>
  <li>
<a href="#working-with-rows" id="toc-working-with-rows" class="nav-link" data-scroll-target="#working-with-rows"><span class="toc-section-number">3.4</span>  Working with Rows</a>
  <ul>
<li><a href="#filter" id="toc-filter" class="nav-link" data-scroll-target="#filter">Filter</a></li>
  <li><a href="#aggregation" id="toc-aggregation" class="nav-link" data-scroll-target="#aggregation">Aggregation</a></li>
  </ul>
</li>
  <li><a href="#merging-data" id="toc-merging-data" class="nav-link" data-scroll-target="#merging-data"><span class="toc-section-number">3.5</span>  Merging Data</a></li>
  </ul><div class="toc-actions"><div><i class="bi bi-github"></i></div><div class="action-links"><p><a href="https://github.com/UCSDPoliMathCamp/MathCamp/edit/main/13_data_wrangling_cleaning.Rmd" class="toc-action">Edit this page</a></p></div></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content"><header id="title-block-header" class="quarto-title-block default"><div class="quarto-title">
<div class="quarto-title-block"><div><h1 class="title"><span id="datawrangling" class="quarto-section-identifier d-none d-lg-block"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">Data Wrangling</span></span></h1><button type="button" class="btn code-tools-button" id="quarto-code-tools-source"><i class="bi"></i> Code</button></div></div>
</div>



<div class="quarto-title-meta">

    
    
  </div>
  

</header><section id="clean-data" class="level2" data-number="3.1"><h2 data-number="3.1" class="anchored" data-anchor-id="clean-data">
<span class="header-section-number">3.1</span> Clean Data</h2>
<p>The raw data used in much of political science research rarely comes to us in a format that is immediately accessible for analysis. Instead, we frequently need to write an R script to “clean” the data first. Only after cleaning the data will it be usable for visualization or statistical modeling. This process (also known as “data wrangling”) can be extremely arduous and time-consuming—depending on how messy the raw data is in the first place. According to the common aphorism, the time you spend writing R code to clean your data sets will far exceed the time you spend subsequently running any sort of statistical analysis on the cleaned data.</p>
<p>Although data cleaning has a reputation as a dull, menial task (compared to the “fun” of statistical modeling), try to avoid treating the process like it is merely a roadblock—something to be overcome before you can begin the <em>real</em> analysis. In fact, each decision you make when wrangling your raw data into its final state <a href="https://counting.substack.com/p/data-cleaning-is-analysis-not-grunt#:~:text=The%20act%20of%20cleaning%20data%20is%20the%20act%20of%20preferentially,the%20act%20of%20data%20analysis.">is a crucial part of the final research product</a>. Whether or not to drop certain observations, or using different levels of data aggregation, are some examples of choices which can have massive downstream effects. You should be thoughtful and transparent about your decision-making process the whole time you spend cleaning data.</p>
</section><section id="cleaning-data-using-dplyr" class="level2" data-number="3.2"><h2 data-number="3.2" class="anchored" data-anchor-id="cleaning-data-using-dplyr">
<span class="header-section-number">3.2</span> Cleaning Data Using dplyr</h2>
<p>As in the other sections of this book, we will be using the Tidyverse approach to data cleaning here. The primary Tidyverse package for data cleaning is <a href="https://dplyr.tidyverse.org/">dplyr</a> and it contains most of the functions we will be using in this chapter.</p>
<p>Rather than downloading a .csv file and using the <code><a href="https://readr.tidyverse.org/reference/read_delim.html">read_csv()</a></code> function to load in our data for this chapter, we will be using a package which contains multiple data sets. The data come from the <a href="https://github.com/dgrtwo/unvotes">United Nations General Assembly</a>. First install the unvotes package by running the following command in your Console.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-1_db8b492b5dd60ca6c6050e6adccb0d11">
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="fu"><a href="https://rdrr.io/r/utils/install.packages.html">install.packages</a></span><span class="op">(</span><span class="st">"unvotes"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Then run</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-2_511fa903c0987dcdfe829eed50deec0b">
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/dgrtwo/unvotes">unvotes</a></span><span class="op">)</span></span>
<span><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://tidyverse.tidyverse.org">tidyverse</a></span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>When you use the <code><a href="https://rdrr.io/r/base/library.html">library()</a></code> function, many packages automatically load small data sets which immediately become available for use. However, accessing these data can be a bit confusing because they do not automatically show up as objects in your Environment tab. Let’s add the unvotes data sets to our Environment with the following chunk of code:</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-3_1f3ff9feaa5c578c8c0bc95ff51484bd">
<div class="sourceCode" id="cb3"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_votes</span> <span class="op">&lt;-</span> <span class="va">un_votes</span></span>
<span><span class="va">un_roll_calls</span> <span class="op">&lt;-</span> <span class="va">un_roll_calls</span></span>
<span><span class="va">un_roll_call_issues</span> <span class="op">&lt;-</span> <span class="va">un_roll_call_issues</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>About the data</p>
<ul>
<li>
<code>un_votes</code>, country-vote level data. Each row is a country’s vote on a particular UN Assembly resolution.</li>
<li>
<code>un_roll_calls</code>, resolution level data. Contains information about each resolution.</li>
<li>
<code>un_roll_call_issues</code>, resolution level data. Contains the issue-area for each resolution.</li>
</ul>
<section id="the-pipe-operator" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="the-pipe-operator">The Pipe Operator</h3>
<p>Before we get started using dplyr we need to first introduce the “pipe” operator <code>|&gt;</code>. Pipes are an extremely convenient tool for linking several functions together. They work by passing the object on the left hand side of the pipe into the function following the pipe. <a href="https://twitter.com/andrewheiss/status/1359583543509348356">Here is an example</a>.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-4_6f5e551ce2ae2924c20b9cf442092172">
<div class="sourceCode" id="cb4"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># The pipe way</span></span>
<span><span class="va">me</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">wake_up</span><span class="op">(</span>time <span class="op">=</span> <span class="st">"8:00"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">get_out_of_bed</span><span class="op">(</span>side <span class="op">=</span> <span class="st">"correct"</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">get_dressed</span><span class="op">(</span>pants <span class="op">=</span> <span class="cn">TRUE</span>, shirt <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu">leave_house</span><span class="op">(</span>car <span class="op">=</span> <span class="cn">FALSE</span>, bike <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span>
<span></span>
<span><span class="co"># The non-pipe way</span></span>
<span><span class="fu">leave_house</span><span class="op">(</span><span class="fu">get_dressed</span><span class="op">(</span><span class="fu">get_out_of_bed</span><span class="op">(</span><span class="fu">wake_up</span><span class="op">(</span><span class="va">me</span>, time <span class="op">=</span> <span class="st">"8:00"</span><span class="op">)</span>, side <span class="op">=</span> <span class="st">"correct"</span><span class="op">)</span>, pants <span class="op">=</span> <span class="cn">TRUE</span>, shirt <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span>, car <span class="op">=</span> <span class="cn">FALSE</span>, bike <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Both code chunks above will end up doing the same thing. But the pipe method is much easier to write, and much easier for others to read and understand.</p>
<p>Before R version 4.1, the pipe operator was only available in the <a href="https://magrittr.tidyverse.org/">magrittr</a> package (which remains part of the Tidyverse). The magrittr pipe is written <code>%&gt;%</code> and many R users continue to use this over the native R <code>|&gt;</code>. There are a few very minor differences between the two pipes, which you should feel free to ignore. We use the native R <code>|&gt;</code> pipe in this book because it is generally a good idea, all else equal, to reduce your dependency on outside packages when writing code.</p>
</section></section><section id="working-with-columns" class="level2" data-number="3.3"><h2 data-number="3.3" class="anchored" data-anchor-id="working-with-columns">
<span class="header-section-number">3.3</span> Working with Columns</h2>
<p>Each column in a data set typically represents a single variable, or attribute, relating to the observation in a particular row. In this section we will look at some of dplyr’s functions for working with columns.</p>
<section id="select" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="select">Select</h3>
<p>The <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> function is primarily used to remove unwanted columns from the data. Here is an example.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-5_db8f5022a48c9d1a255f61b130dd0cf6">
<div class="sourceCode" id="cb5"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_roll_calls</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">rcid</span>, <span class="va">date</span><span class="op">)</span> <span class="co"># Keeping only two variables</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6,202 × 2
    rcid date      
   &lt;int&gt; &lt;date&gt;    
 1     3 1946-01-01
 2     4 1946-01-02
 3     5 1946-01-04
 4     6 1946-01-04
 5     7 1946-01-02
 6     8 1946-01-05
 7     9 1946-02-05
 8    10 1946-02-05
 9    11 1946-02-05
10    12 1946-02-06
# … with 6,192 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>Note that the code chunk above did not alter the data set object <code>un_roll_calls</code>. If we wanted to take this smaller data set and use it for something else, we will need to use the assignment operator <code>&lt;-</code> to save our work.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-6_c57bda7813b9b818a49915806aa917c5">
<div class="sourceCode" id="cb7"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># This creates a new object called "small_un_roll_calls"</span></span>
<span><span class="co"># containing only rcid and date columns</span></span>
<span><span class="va">small_un_roll_calls</span> <span class="op">&lt;-</span> <span class="va">un_roll_calls</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">rcid</span>, <span class="va">date</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> function can be very versatile. Rather than typing every column name we want to keep, it is often faster to specify the columns we want to drop.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-7_a320bfb032fe77b7a3b156f7c6a972e3">
<div class="sourceCode" id="cb8"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_roll_calls</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="op">-</span><span class="va">session</span><span class="op">)</span> <span class="co"># Keep everything except session column</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6,202 × 8
    rcid importantvote date       unres   amend  para short                descr
   &lt;int&gt;         &lt;int&gt; &lt;date&gt;     &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;chr&gt;                &lt;chr&gt;
 1     3             0 1946-01-01 R/1/66      1     0 AMENDMENTS, RULES O… "TO …
 2     4             0 1946-01-02 R/1/79      0     0 SECURITY COUNCIL EL… "TO …
 3     5             0 1946-01-04 R/1/98      0     0 VOTING PROCEDURE     "TO …
 4     6             0 1946-01-04 R/1/107     0     0 DECLARATION OF HUMA… "TO …
 5     7             0 1946-01-02 R/1/295     1     0 GENERAL ASSEMBLY EL… "TO …
 6     8             0 1946-01-05 R/1/297     1     0 ECOSOC POWERS        "TO …
 7     9             0 1946-02-05 R/1/329     0     0 POST-WAR RECONSTRUC… "TO …
 8    10             0 1946-02-05 R/1/361     1     1 U.N. MEMBERS, RELAT… "TO …
 9    11             0 1946-02-05 R/1/376     0     0 TRUSTEESHIP AMENDME… "TO …
10    12             0 1946-02-06 R/1/394     1     1 COUNCIL MEMBER TERM… "TO …
# … with 6,192 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>There are many other convenient ways to selection columns (e.g.&nbsp;by common names, by type of data, or by position in the data set). For a full list of ways to use <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> see <a href="https://dplyr.tidyverse.org/reference/select.html">this link</a>. Here is one example of selecting every column which is a “character” type.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-8_9461702a37ecfb664486c9a1a458f374">
<div class="sourceCode" id="cb10"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_roll_calls</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="fu">where</span><span class="op">(</span><span class="va">is.character</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6,202 × 3
   unres   short                              descr                             
   &lt;chr&gt;   &lt;chr&gt;                              &lt;chr&gt;                             
 1 R/1/66  AMENDMENTS, RULES OF PROCEDURE     "TO ADOPT A CUBAN AMENDMENT TO TH…
 2 R/1/79  SECURITY COUNCIL ELECTIONS         "TO ADOPT A USSR PROPOSAL ADJOURN…
 3 R/1/98  VOTING PROCEDURE                   "TO ADOPT THE KOREAN PROPOSAL THA…
 4 R/1/107 DECLARATION OF HUMAN RIGHTS        "TO ADOPT A CUBAN PROPOSAL (A/3-C…
 5 R/1/295 GENERAL ASSEMBLY ELECTIONS         "TO ADOPT A 6TH COMMITTEE AMENDME…
 6 R/1/297 ECOSOC POWERS                      "TO ADOPT A SECOND 6TH COMM. AMEN…
 7 R/1/329 POST-WAR RECONSTRUCTION            "TO OPEN THE DISCUSSION ON THE PO…
 8 R/1/361 U.N. MEMBERS, RELATIONS WITH SPAIN "TO ADOPT GENERAL COMM. DRAFT RES…
 9 R/1/376 TRUSTEESHIP AMENDMENTS             "TO ADOPT DRAFT RESOLUTIONS I AND…
10 R/1/394 COUNCIL MEMBER TERM LENGTH         "TO ADOPT PARAGRAPH (A) OF THE 6T…
# … with 6,192 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>Lastly, we can use <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> to rename columns in our data. The chunk of code below selects the “unres” and date columns, and renames “unres” to “un_resolution” at the same time.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-9_21ba63b1acf4a129a90f8acbebfd9fd3">
<div class="sourceCode" id="cb12"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_roll_calls</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span>un_resolution <span class="op">=</span> <span class="va">unres</span>, <span class="va">date</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6,202 × 2
   un_resolution date      
   &lt;chr&gt;         &lt;date&gt;    
 1 R/1/66        1946-01-01
 2 R/1/79        1946-01-02
 3 R/1/98        1946-01-04
 4 R/1/107       1946-01-04
 5 R/1/295       1946-01-02
 6 R/1/297       1946-01-05
 7 R/1/329       1946-02-05
 8 R/1/361       1946-02-05
 9 R/1/376       1946-02-05
10 R/1/394       1946-02-06
# … with 6,192 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>If you only want to rename columns—without specifying which to select—dplyr has a function <code><a href="https://dplyr.tidyverse.org/reference/rename.html">rename()</a></code> for this purpose. The syntax is similar to the code chunk above <code>new_variable_name = original_variable_name</code>. This code will keep all columns and change the names of the specified variables.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-10_6b462cb3c764b58f605829beb2fc1d88">
<div class="sourceCode" id="cb14"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_roll_calls</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/rename.html">rename</a></span><span class="op">(</span>un_resolution <span class="op">=</span> <span class="va">unres</span>,</span>
<span>         amendment <span class="op">=</span> <span class="va">amend</span>,</span>
<span>         paragraph <span class="op">=</span> <span class="va">para</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6,202 × 9
    rcid session importantvote date       un_resol…¹ amend…² parag…³ short descr
   &lt;int&gt;   &lt;dbl&gt;         &lt;int&gt; &lt;date&gt;     &lt;chr&gt;        &lt;int&gt;   &lt;int&gt; &lt;chr&gt; &lt;chr&gt;
 1     3       1             0 1946-01-01 R/1/66           1       0 AMEN… "TO …
 2     4       1             0 1946-01-02 R/1/79           0       0 SECU… "TO …
 3     5       1             0 1946-01-04 R/1/98           0       0 VOTI… "TO …
 4     6       1             0 1946-01-04 R/1/107          0       0 DECL… "TO …
 5     7       1             0 1946-01-02 R/1/295          1       0 GENE… "TO …
 6     8       1             0 1946-01-05 R/1/297          1       0 ECOS… "TO …
 7     9       1             0 1946-02-05 R/1/329          0       0 POST… "TO …
 8    10       1             0 1946-02-05 R/1/361          1       1 U.N.… "TO …
 9    11       1             0 1946-02-05 R/1/376          0       0 TRUS… "TO …
10    12       1             0 1946-02-06 R/1/394          1       1 COUN… "TO …
# … with 6,192 more rows, and abbreviated variable names ¹​un_resolution,
#   ²​amendment, ³​paragraph
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
</section><section id="mutate" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="mutate">Mutate</h3>
<p>The <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/rename.html">rename()</a></code> functions are great for tidying up your data sets, but they do not change the underlying variables. To change existing variables or to create new ones we use <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>.</p>
<p>Let’s say we discovered that all the roll call IDs in the column “rcid” were supposed to be in multiples of 10. The code chunk below creates a new variable called “rcid_10” which is simply the value of the original “rcid” variable multiplied by 10.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-11_48508537eaf3368c1ec70f121c1a9ea0">
<div class="sourceCode" id="cb16"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_votes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>rcid_10 <span class="op">=</span> <span class="va">rcid</span> <span class="op">*</span> <span class="fl">10</span><span class="op">)</span> <span class="co"># Creates the new rcid_10 variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 869,937 × 5
    rcid country            country_code vote  rcid_10
   &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;        &lt;fct&gt;   &lt;dbl&gt;
 1     3 United States      US           yes        30
 2     3 Canada             CA           no         30
 3     3 Cuba               CU           yes        30
 4     3 Haiti              HT           yes        30
 5     3 Dominican Republic DO           yes        30
 6     3 Mexico             MX           yes        30
 7     3 Guatemala          GT           yes        30
 8     3 Honduras           HN           yes        30
 9     3 El Salvador        SV           yes        30
10     3 Nicaragua          NI           yes        30
# … with 869,927 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>If you didn’t want to create a brand new variable, but instead wanted to overwrite the original variable, you just need to put the original variable to the left of the <code>=</code> in <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-12_510a313c0f7778211aefe83110b5d1f6">
<div class="sourceCode" id="cb18"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_votes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>rcid <span class="op">=</span> <span class="va">rcid</span> <span class="op">*</span> <span class="fl">10</span><span class="op">)</span> <span class="co"># Overwrites the existing rcid variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 869,937 × 4
    rcid country            country_code vote 
   &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;        &lt;fct&gt;
 1    30 United States      US           yes  
 2    30 Canada             CA           no   
 3    30 Cuba               CU           yes  
 4    30 Haiti              HT           yes  
 5    30 Dominican Republic DO           yes  
 6    30 Mexico             MX           yes  
 7    30 Guatemala          GT           yes  
 8    30 Honduras           HN           yes  
 9    30 El Salvador        SV           yes  
10    30 Nicaragua          NI           yes  
# … with 869,927 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>We commonly need to create a new variable whose values depend on the values of one of the original variables. The function <code><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when()</a></code> helps us do this inside <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-13_5d3c0208ff805f7bb9cc2b33c16ae2cb">
<div class="sourceCode" id="cb20"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_votes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>vote_dummy <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span><span class="va">vote</span> <span class="op">==</span> <span class="st">"yes"</span> <span class="op">~</span> <span class="fl">1</span>,</span>
<span>                                <span class="va">vote</span> <span class="op">==</span> <span class="st">"no"</span> <span class="op">~</span> <span class="fl">0</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 869,937 × 5
    rcid country            country_code vote  vote_dummy
   &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;        &lt;fct&gt;      &lt;dbl&gt;
 1     3 United States      US           yes            1
 2     3 Canada             CA           no             0
 3     3 Cuba               CU           yes            1
 4     3 Haiti              HT           yes            1
 5     3 Dominican Republic DO           yes            1
 6     3 Mexico             MX           yes            1
 7     3 Guatemala          GT           yes            1
 8     3 Honduras           HN           yes            1
 9     3 El Salvador        SV           yes            1
10     3 Nicaragua          NI           yes            1
# … with 869,927 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>As you can see, the code chunk above creates a new variable called “vote_dummy” which takes the value <code>1</code> if “vote” equals <code>"yes"</code> and takes the values <code>0</code> if “vote” equals <code>"no"</code>. Like other programming languages, R uses the <code>==</code> logical operator to check whether a value <em>equals</em>, or is equivalent, to some other value. This is different from the single <code>=</code> which is used to create entire new variables inside <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>.</p>
<p>Here is one more example using <code><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when()</a></code>.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-14_0c228745173807ec51383d7fda411a26">
<div class="sourceCode" id="cb22"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_votes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>rcid_era <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span><span class="va">rcid</span> <span class="op">&lt;</span> <span class="fl">2000</span> <span class="op">~</span> <span class="st">"old"</span>,</span>
<span>                              <span class="va">rcid</span> <span class="op">&gt;=</span> <span class="fl">2000</span> <span class="op">&amp;</span> <span class="va">rcid</span> <span class="op">&lt;</span> <span class="fl">6000</span> <span class="op">~</span> <span class="st">"middle"</span>,</span>
<span>                              <span class="va">rcid</span> <span class="op">&gt;=</span> <span class="fl">6000</span> <span class="op">~</span> <span class="st">"recent"</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 869,937 × 5
    rcid country            country_code vote  rcid_era
   &lt;dbl&gt; &lt;chr&gt;              &lt;chr&gt;        &lt;fct&gt; &lt;chr&gt;   
 1     3 United States      US           yes   old     
 2     3 Canada             CA           no    old     
 3     3 Cuba               CU           yes   old     
 4     3 Haiti              HT           yes   old     
 5     3 Dominican Republic DO           yes   old     
 6     3 Mexico             MX           yes   old     
 7     3 Guatemala          GT           yes   old     
 8     3 Honduras           HN           yes   old     
 9     3 El Salvador        SV           yes   old     
10     3 Nicaragua          NI           yes   old     
# … with 869,927 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>The new variable “rcid_era” takes three values, <code>"old"</code>, <code>"middle"</code>, and <code>"recent"</code> based on what range the “rcid” variable falls within.</p>
<p>To recap, the most commonly used functions for cleaning columns/variables in your data are:</p>
<ul>
<li>
<code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code> removes and/or renames columns.</li>
<li>
<code><a href="https://dplyr.tidyverse.org/reference/rename.html">rename()</a></code> renames existing columns without removing any.</li>
<li>
<code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code> changes the values of existing columns and creates new columns.</li>
</ul></section></section><section id="working-with-rows" class="level2" data-number="3.4"><h2 data-number="3.4" class="anchored" data-anchor-id="working-with-rows">
<span class="header-section-number">3.4</span> Working with Rows</h2>
<section id="filter" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="filter">Filter</h3>
<p>Dplyr’s primary function for removing unwanted rows is <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>. Like we saw when using <code><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when()</a></code> inside <code><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate()</a></code>, using <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> requires some practice with logical operators. The function <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> works by specifying some variable and only keeping rows in the data for which the logical operation evaluates to <code>TRUE</code>. Here is an example.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-15_d97f38668769a783ca2637db9fbdce36">
<div class="sourceCode" id="cb24"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_roll_calls</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">importantvote</span> <span class="op">==</span> <span class="fl">1</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 411 × 9
    rcid session importantvote date       unres     amend  para short      descr
   &lt;int&gt;   &lt;dbl&gt;         &lt;int&gt; &lt;date&gt;     &lt;chr&gt;     &lt;int&gt; &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;
 1  2491      38             1 1983-10-04 R/38/3        0     0 KAMPUCHEA  TO R…
 2  2492      38             1 1983-11-06 R/38/7        0     0 GRENADA, … TO D…
 3  2497      38             1 1983-11-06 R/38/29       0     0 AFGHANIST… TO D…
 4  2504      38             1 1983-12-06 R/38/39A      0     0 APARTHEID… TO A…
 5  2510      38             1 1983-12-06 R/38/39G      0     0 SOUTH AFR… TO R…
 6  2526      38             1 1983-12-06 R/38/180E     0     0 ISRAEL, I… TO O…
 7  2563      38             1 1983-12-07 R/38/187C     0     0 CHEMICAL,… TO N…
 8  2610      38             1 1983-12-03 R/38/101      0     0 HUMAN RIG… TO E…
 9  2641      39             1 1984-10-04 R/39/5        0     0 KAMPUCHEA  TO R…
10  2645      39             1 1984-11-02 R/39/13       0     0 AFGHANIST… TO R…
# … with 401 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>The original “un_roll_calls” data set object has 6202 rows, whereas this new data set only has 411 rows. This is because we filtered out any row in which the variable “importantvote” was not equal to <code>1</code>. Like <code><a href="https://dplyr.tidyverse.org/reference/select.html">select()</a></code>, we can extend the use of <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> in many ways.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-16_ffa5986fa428efff5032c6d678d15d8d">
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># &amp; for AND</span></span>
<span><span class="va">un_roll_calls</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">importantvote</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">&amp;</span> <span class="va">session</span> <span class="op">&gt;</span> <span class="fl">40</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 386 × 9
    rcid session importantvote date       unres     amend  para short      descr
   &lt;int&gt;   &lt;dbl&gt;         &lt;int&gt; &lt;date&gt;     &lt;chr&gt;     &lt;int&gt; &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;
 1  2948      41             1 1986-10-03 R/41/6       NA    NA KAMPUCHEA  The …
 2  2957      41             1 1986-11-02 R/41/31      NA    NA NICARAGUA… Urge…
 3  2958      41             1 1986-11-04 R/41/33      NA    NA AFGHANIST… The …
 4  2967      41             1 1986-11-05 R/41/38      NA    NA LIBYA, U.… Decl…
 5  2968      41             1 1986-11-05 R/41/39A     NA    NA NAMIBIA, … Situ…
 6  2996      41             1 1986-12-04 R/41/58C     NA    NA CHEMICAL,… Proh…
 7  3075      41             1 1986-12-05 R/41/158     NA    NA HUMAN RIG… Ques…
 8  3078      41             1 1986-12-05 R/41/162A    NA    NA MIDDLE EA… Reaf…
 9  3098      41             1 1986-12-05 R/41/211A    NA    NA BUDGET, 1… Revi…
10  3099      41             1 1986-12-05 R/41/211B    NA    NA BUDGET, 1… Revi…
# … with 376 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># | for OR</span></span>
<span><span class="va">un_roll_calls</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">importantvote</span> <span class="op">==</span> <span class="fl">1</span> <span class="op">|</span> <span class="va">session</span> <span class="op">&gt;</span> <span class="fl">40</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 3,228 × 9
    rcid session importantvote date       unres     amend  para short      descr
   &lt;int&gt;   &lt;dbl&gt;         &lt;int&gt; &lt;date&gt;     &lt;chr&gt;     &lt;int&gt; &lt;int&gt; &lt;chr&gt;      &lt;chr&gt;
 1  2491      38             1 1983-10-04 R/38/3        0     0 KAMPUCHEA  TO R…
 2  2492      38             1 1983-11-06 R/38/7        0     0 GRENADA, … TO D…
 3  2497      38             1 1983-11-06 R/38/29       0     0 AFGHANIST… TO D…
 4  2504      38             1 1983-12-06 R/38/39A      0     0 APARTHEID… TO A…
 5  2510      38             1 1983-12-06 R/38/39G      0     0 SOUTH AFR… TO R…
 6  2526      38             1 1983-12-06 R/38/180E     0     0 ISRAEL, I… TO O…
 7  2563      38             1 1983-12-07 R/38/187C     0     0 CHEMICAL,… TO N…
 8  2610      38             1 1983-12-03 R/38/101      0     0 HUMAN RIG… TO E…
 9  2641      39             1 1984-10-04 R/39/5        0     0 KAMPUCHEA  TO R…
10  2645      39             1 1984-11-02 R/39/13       0     0 AFGHANIST… TO R…
# … with 3,218 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>The first chunk above filters out all rows in which “importantvote” did not equal <code>1</code> <strong>AND</strong> “session” was less than <code>40</code>. The second chunk above filters out all rows in which “importantvote” did not equal <code>1</code> <strong>OR</strong> “session” was less than <code>40</code>.</p>
<p>Removing missing, or <code>NA</code>, values is another common job for <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>. To do this you can use the function <code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code> inside <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>. The function <code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code> evaluates to <code>TRUE</code> if the variable’s value is <code>NA</code> and evaluates to <code>FALSE</code> otherwise. Because <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> only keeps rows where the condition evaluates to <code>TRUE</code>, in order to <em>remove</em> <code>NA</code> values we need to negate <code><a href="https://rdrr.io/r/base/NA.html">is.na()</a></code> with the <code>!</code> operator. The <code>!</code> operator flips the truthiness of any logical statement it precedes.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-17_de156b6a068e9bfd643a0faad57755d1">
<div class="sourceCode" id="cb30"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_roll_calls</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">amend</span><span class="op">)</span><span class="op">)</span> <span class="co"># Removing rows with NA for the amend variable</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 2,868 × 9
    rcid session importantvote date       unres   amend  para short        descr
   &lt;int&gt;   &lt;dbl&gt;         &lt;int&gt; &lt;date&gt;     &lt;chr&gt;   &lt;int&gt; &lt;int&gt; &lt;chr&gt;        &lt;chr&gt;
 1     3       1             0 1946-01-01 R/1/66      1     0 AMENDMENTS,… "TO …
 2     4       1             0 1946-01-02 R/1/79      0     0 SECURITY CO… "TO …
 3     5       1             0 1946-01-04 R/1/98      0     0 VOTING PROC… "TO …
 4     6       1             0 1946-01-04 R/1/107     0     0 DECLARATION… "TO …
 5     7       1             0 1946-01-02 R/1/295     1     0 GENERAL ASS… "TO …
 6     8       1             0 1946-01-05 R/1/297     1     0 ECOSOC POWE… "TO …
 7     9       1             0 1946-02-05 R/1/329     0     0 POST-WAR RE… "TO …
 8    10       1             0 1946-02-05 R/1/361     1     1 U.N. MEMBER… "TO …
 9    11       1             0 1946-02-05 R/1/376     0     0 TRUSTEESHIP… "TO …
10    12       1             0 1946-02-06 R/1/394     1     1 COUNCIL MEM… "TO …
# … with 2,858 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>It can be confusing to think in terms of logical statements, especially when negation is involved! But you will become more comfortable with <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> the more you practice.</p>
<p>Another handy logical operator is <code>%in%</code>. This lets you specify several values at once when checking whether to keep rows in <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code>.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-18_2fd7c86236e8e37f6ee827cad3699c78">
<div class="sourceCode" id="cb32"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Cumbersome way</span></span>
<span><span class="va">un_votes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">country</span> <span class="op">==</span> <span class="st">"Kenya"</span> <span class="op">|</span></span>
<span>         <span class="va">country</span> <span class="op">==</span> <span class="st">"Grenada"</span> <span class="op">|</span></span>
<span>         <span class="va">country</span> <span class="op">==</span> <span class="st">"Canada"</span> <span class="op">|</span></span>
<span>         <span class="va">country</span> <span class="op">==</span> <span class="st">"Latvia"</span> <span class="op">|</span></span>
<span>         <span class="va">country</span> <span class="op">==</span> <span class="st">"Yemen"</span> <span class="op">|</span></span>
<span>         <span class="va">country</span> <span class="op">==</span> <span class="st">"Angola"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23,324 × 4
    rcid country country_code vote 
   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;        &lt;fct&gt;
 1     3 Canada  CA           no   
 2     4 Canada  CA           no   
 3     5 Canada  CA           no   
 4     6 Canada  CA           no   
 5     7 Canada  CA           no   
 6     8 Canada  CA           yes  
 7     9 Canada  CA           yes  
 8    10 Canada  CA           yes  
 9    11 Canada  CA           yes  
10    12 Canada  CA           yes  
# … with 23,314 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Easier way</span></span>
<span><span class="va">country_list</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"Kenya"</span>, <span class="st">"Grenada"</span>, <span class="st">"Canada"</span>,</span>
<span>                  <span class="st">"Latvia"</span>, <span class="st">"Yemen"</span>, <span class="st">"Angola"</span><span class="op">)</span></span>
<span><span class="va">un_votes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">country</span> <span class="op"><a href="https://rdrr.io/r/base/match.html">%in%</a></span> <span class="va">country_list</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 23,324 × 4
    rcid country country_code vote 
   &lt;dbl&gt; &lt;chr&gt;   &lt;chr&gt;        &lt;fct&gt;
 1     3 Canada  CA           no   
 2     4 Canada  CA           no   
 3     5 Canada  CA           no   
 4     6 Canada  CA           no   
 5     7 Canada  CA           no   
 6     8 Canada  CA           yes  
 7     9 Canada  CA           yes  
 8    10 Canada  CA           yes  
 9    11 Canada  CA           yes  
10    12 Canada  CA           yes  
# … with 23,314 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>The two chunks of code above will produce the same filtered data set, but the second chunk requires fewer lines of code and is more flexible if we want to add or remove countries.</p>
</section><section id="aggregation" class="level3 unnumbered"><h3 class="unnumbered anchored" data-anchor-id="aggregation">Aggregation</h3>
<p>Filtering is great for removing unwanted rows in your data. However, after using <code><a href="https://dplyr.tidyverse.org/reference/filter.html">filter()</a></code> the data set’s unit of analysis typically remains the same. In the code chunk above, for example, we removed most of the countries from our data, but each row in the resulting data set is still a unique country-vote observation.</p>
<p>Let’s say we want to reduce the data set down to the country level, rather than country-vote level, and examine the proportion of “no” votes taken by each country. We can do this in dplyr using the pair of functions <code><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by()</a></code> and <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code>. Here is an example.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-19_32f3e0c81d13e8b29a665a915cb59694">
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_votes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Creating a new numeric dummy vote variable</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>vote_dummy <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span><span class="va">vote</span> <span class="op">==</span> <span class="st">"yes"</span> <span class="op">~</span> <span class="fl">1</span>,</span>
<span>                                <span class="va">vote</span> <span class="op">==</span> <span class="st">"no"</span> <span class="op">~</span> <span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Specify level of aggregation</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">country</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="co"># Perform the aggregation function by group</span></span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>proportion_yes_vote <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">vote_dummy</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 200 × 2
   country           proportion_yes_vote
   &lt;chr&gt;                           &lt;dbl&gt;
 1 Afghanistan                     0.938
 2 Albania                         0.816
 3 Algeria                         0.965
 4 Andorra                         0.833
 5 Angola                          0.985
 6 Antigua &amp; Barbuda               0.988
 7 Argentina                       0.935
 8 Armenia                         0.950
 9 Australia                       0.745
10 Austria                         0.880
# … with 190 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
</div>
<p>The code above uses the function <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> to calculate the average value of “vote_dummy” within each country. Because “vote_dummy” takes the values <code>1</code> and <code>0</code>, this average can be interpreted as a proportion of 1’s, or “yes” votes. We need to add <code>na.rm = TRUE</code> inside <code><a href="https://rdrr.io/r/base/mean.html">mean()</a></code> to tell R to ignore <code>NA</code> values when calculating this average.</p>
<p>If we want to sort our data by the new aggregated column, we can do so using <code><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange()</a></code> after <code><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize()</a></code>.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-20_5ec2ba40801444c7b34e213d52328822">
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_votes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>vote_dummy <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/case_when.html">case_when</a></span><span class="op">(</span><span class="va">vote</span> <span class="op">==</span> <span class="st">"yes"</span> <span class="op">~</span> <span class="fl">1</span>,</span>
<span>                                <span class="va">vote</span> <span class="op">==</span> <span class="st">"no"</span> <span class="op">~</span> <span class="fl">0</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">country</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>proportion_yes_vote <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/mean.html">mean</a></span><span class="op">(</span><span class="va">vote_dummy</span>, na.rm <span class="op">=</span> <span class="cn">TRUE</span><span class="op">)</span><span class="op">)</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/arrange.html">arrange</a></span><span class="op">(</span><span class="va">proportion_yes_vote</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 200 × 2
   country                          proportion_yes_vote
   &lt;chr&gt;                                          &lt;dbl&gt;
 1 United States                                  0.369
 2 Israel                                         0.464
 3 Palau                                          0.541
 4 Micronesia (Federated States of)               0.604
 5 United Kingdom                                 0.616
 6 Marshall Islands                               0.659
 7 France                                         0.662
 8 Federal Republic of Germany                    0.682
 9 Canada                                         0.701
10 Belgium                                        0.714
# … with 190 more rows
# ℹ Use `print(n = ...)` to see more rows</code></pre>
</div>
<div class="sourceCode" id="cb40"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="co"># Use arrange(desc(proportion_yes_vote))</span></span>
<span><span class="co"># to sort in descending order</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The United States votes “No” at a much higher rate than other countries!</p>
<p>Lastly, the dplyr function <code><a href="https://dplyr.tidyverse.org/reference/count.html">count()</a></code> is very handy for quickly tallying the number of observations within each category of a variable. Simply put the name of the variable you want to count inside <code><a href="https://dplyr.tidyverse.org/reference/count.html">count()</a></code> and voila.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-21_8e3148c22d78763dfcaed01b9ef89569">
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_roll_call_issues</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/count.html">count</a></span><span class="op">(</span><span class="va">issue</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 6 × 2
  issue                                    n
  &lt;fct&gt;                                &lt;int&gt;
1 Colonialism                            957
2 Arms control and disarmament          1092
3 Economic development                   765
4 Human rights                          1015
5 Palestinian conflict                  1061
6 Nuclear weapons and nuclear material   855</code></pre>
</div>
</div>
</section></section><section id="merging-data" class="level2" data-number="3.5"><h2 data-number="3.5" class="anchored" data-anchor-id="merging-data">
<span class="header-section-number">3.5</span> Merging Data</h2>
<p>So far we have only been working with one data set at a time. But it is rare to find all the data you need for a particular project in one single data set. Frequently we will have to merge data sets together in order to have all our variables in the same place. The most common way to merge data using dplyr is with the <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> function.</p>
<p>To illustrate how <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> works, let’s say we have two data sets: our main data set, <code>x</code> and the data set we want to merge, <code>y</code>. Here is an example:</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-22_992703132ae222594b8663e21719ef94">
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">xy_data</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">x</span>, <span class="va">y</span>, by <span class="op">=</span> <span class="st">"key_variable"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>The new data set <code>xy_data</code> is produced by merging the <code>y</code> data set <em>into</em> the <code>x</code> data set based on the shared value of the <code>key_variable</code> variable. Left joins will always keep all rows in the <code>x</code> data set, but will only merge in rows from <code>y</code> if they match up with the <code>key_variable</code>. Your key variable will typically be something like country ID code or a unit’s name in the data. Because we like to use pipes in this course, the chunk of code above can be rewritten as:</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-23_3342ca51428fa77f270b81c5c2819b87">
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">xy_data</span> <span class="op">&lt;-</span> <span class="va">x</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">y</span>, by <span class="op">=</span> <span class="st">"key_variable"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Now let’s take a look at <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> using real data from the unvotes data set.</p>
<div class="cell" data-hash="13_data_wrangling_cleaning_cache/html/unnamed-chunk-24_cd96a10b81395ba4f0341e1035e424ab">
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r code-with-copy"><code class="sourceCode R"><span><span class="va">un_votes</span> <span class="op">|&gt;</span> </span>
<span>  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join</a></span><span class="op">(</span><span class="va">un_roll_calls</span>, by <span class="op">=</span> <span class="st">"rcid"</span><span class="op">)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 869,937 × 12
    rcid country      count…¹ vote  session impor…² date       unres amend  para
   &lt;dbl&gt; &lt;chr&gt;        &lt;chr&gt;   &lt;fct&gt;   &lt;dbl&gt;   &lt;int&gt; &lt;date&gt;     &lt;chr&gt; &lt;int&gt; &lt;int&gt;
 1     3 United Stat… US      yes         1       0 1946-01-01 R/1/…     1     0
 2     3 Canada       CA      no          1       0 1946-01-01 R/1/…     1     0
 3     3 Cuba         CU      yes         1       0 1946-01-01 R/1/…     1     0
 4     3 Haiti        HT      yes         1       0 1946-01-01 R/1/…     1     0
 5     3 Dominican R… DO      yes         1       0 1946-01-01 R/1/…     1     0
 6     3 Mexico       MX      yes         1       0 1946-01-01 R/1/…     1     0
 7     3 Guatemala    GT      yes         1       0 1946-01-01 R/1/…     1     0
 8     3 Honduras     HN      yes         1       0 1946-01-01 R/1/…     1     0
 9     3 El Salvador  SV      yes         1       0 1946-01-01 R/1/…     1     0
10     3 Nicaragua    NI      yes         1       0 1946-01-01 R/1/…     1     0
# … with 869,927 more rows, 2 more variables: short &lt;chr&gt;, descr &lt;chr&gt;, and
#   abbreviated variable names ¹​country_code, ²​importantvote
# ℹ Use `print(n = ...)` to see more rows, and `colnames()` to see all variable names</code></pre>
</div>
</div>
<p>The code chunk above merged all the variables from the <code>un_roll_calls</code> data set into the <code>un_votes</code> data set. Recall that the <code>un_votes</code> data contains information about how countries voted on particular UN roll call votes, and the <code>un_roll_calls</code> data contains information about the specific votes (such as whether the vote was an “importantvote”). If there were any rows in <code>un_roll_calls</code> that had <code>rcid</code> values which failed to match with an <code>rcid</code> value in <code>un_votes</code>, the row would not get merged.</p>
<p>While <code><a href="https://dplyr.tidyverse.org/reference/mutate-joins.html">left_join()</a></code> is far and away the most common, and useful, way to merge two data sets when using dplyr, there are various other types of merges which have their niche applications. For a more in-depth look at merging data in dplyr see <a href="https://github.com/gadenbuie/tidyexplain">this page</a> with helpful animations.</p>
<!-- un_votes |>  -->
<!--   left_join(un_roll_call_issues, by = "rcid") -->
<!-- un_roll_calls |>  -->
<!--   left_join(un_roll_call_issues) -->
<!-- ## Reshaping Data -->
<!-- ```{r} -->
<!-- wide_un_votes <- un_votes |>  -->
<!--   pivot_wider(id_cols = rcid, -->
<!--               values_from = vote, -->
<!--               names_from = country) -->
<!-- head(wide_un_votes) -->
<!-- ``` -->
<!-- ```{r} -->
<!-- long_un_votes <- wide_un_votes |>  -->
<!--   pivot_longer(cols = -rcid, -->
<!--                names_to = "country", -->
<!--                values_to = "vote") -->
<!-- long_un_votes -->
<!-- ``` -->


<!-- -->

</section></main><!-- /main --><script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    target: function(trigger) {
      return trigger.previousElementSibling;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    setTimeout(function() {
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  const viewSource = window.document.getElementById('quarto-view-source') ||
                     window.document.getElementById('quarto-code-tools-source');
  if (viewSource) {
    const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
    viewSource.addEventListener("click", function(e) {
      if (sourceUrl) {
        // rstudio viewer pane
        if (/\bcapabilities=\b/.test(window.location)) {
          window.open(sourceUrl);
        } else {
          window.location.href = sourceUrl;
        }
      } else {
        const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
        modal.show();
      }
      return false;
    });
  }
  function toggleCodeHandler(show) {
    return function(e) {
      const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
      for (let i=0; i<detailsSrc.length; i++) {
        const details = detailsSrc[i].parentElement;
        if (show) {
          details.open = true;
        } else {
          details.removeAttribute("open");
        }
      }
      const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
      const fromCls = show ? "hidden" : "unhidden";
      const toCls = show ? "unhidden" : "hidden";
      for (let i=0; i<cellCodeDivs.length; i++) {
        const codeDiv = cellCodeDivs[i];
        if (codeDiv.classList.contains(fromCls)) {
          codeDiv.classList.remove(fromCls);
          codeDiv.classList.add(toCls);
        } 
      }
      return false;
    }
  }
  const hideAllCode = window.document.getElementById("quarto-hide-all-code");
  if (hideAllCode) {
    hideAllCode.addEventListener("click", toggleCodeHandler(false));
  }
  const showAllCode = window.document.getElementById("quarto-show-all-code");
  if (showAllCode) {
    showAllCode.addEventListener("click", toggleCodeHandler(true));
  }
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const cites = ref.parentNode.getAttribute('data-cites').split(' ');
    tippyHover(ref, function() {
      var popup = window.document.createElement('div');
      cites.forEach(function(cite) {
        var citeDiv = window.document.createElement('div');
        citeDiv.classList.add('hanging-indent');
        citeDiv.classList.add('csl-entry');
        var biblioDiv = window.document.getElementById('ref-' + cite);
        if (biblioDiv) {
          citeDiv.innerHTML = biblioDiv.innerHTML;
        }
        popup.appendChild(citeDiv);
      });
      return popup.innerHTML;
    });
  }
});
</script><nav class="page-navigation"><div class="nav-page nav-page-previous">
      <a href="./12_visualization.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Visualization</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./14_loops_simulations.html" class="pagination-link">
        <span class="nav-page-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Loops and Simulation</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav><div class="modal fade" id="quarto-embedded-source-code-modal" tabindex="-1" aria-labelledby="quarto-embedded-source-code-modal-label" aria-hidden="true"><div class="modal-dialog modal-dialog-scrollable"><div class="modal-content"><div class="modal-header"><h5 class="modal-title" id="quarto-embedded-source-code-modal-label">Source Code</h5><button class="btn-close" data-bs-dismiss="modal"></button></div><div class="modal-body"><div class="">
<div class="sourceCode" id="cb47" data-shortcodes="false"><pre class="sourceCode markdown code-with-copy"><code class="sourceCode markdown"><span id="cb47-1"><a href="#cb47-1" aria-hidden="true" tabindex="-1"></a><span class="fu"># Data Wrangling {#datawrangling}</span></span>
<span id="cb47-2"><a href="#cb47-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-3"><a href="#cb47-3" aria-hidden="true" tabindex="-1"></a><span class="fu">## Clean Data</span></span>
<span id="cb47-4"><a href="#cb47-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-5"><a href="#cb47-5" aria-hidden="true" tabindex="-1"></a>The raw data used in much of political science research rarely comes to us in a format that is immediately accessible for analysis. Instead, we frequently need to write an R script to "clean" the data first. Only after cleaning the data will it be usable for visualization or statistical modeling. This process (also known as "data wrangling") can be extremely arduous and time-consuming---depending on how messy the raw data is in the first place. According to the common aphorism, the time you spend writing R code to clean your data sets will far exceed the time you spend subsequently running any sort of statistical analysis on the cleaned data.</span>
<span id="cb47-6"><a href="#cb47-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-7"><a href="#cb47-7" aria-hidden="true" tabindex="-1"></a>Although data cleaning has a reputation as a dull, menial task (compared to the "fun" of statistical modeling), try to avoid treating the process like it is merely a roadblock---something to be overcome before you can begin the *real* analysis. In fact, each decision you make when wrangling your raw data into its final state <span class="co">[</span><span class="ot">is a crucial part of the final research product</span><span class="co">](https://counting.substack.com/p/data-cleaning-is-analysis-not-grunt#:~:text=The%20act%20of%20cleaning%20data%20is%20the%20act%20of%20preferentially,the%20act%20of%20data%20analysis.)</span>. Whether or not to drop certain observations, or using different levels of data aggregation, are some examples of choices which can have massive downstream effects. You should be thoughtful and transparent about your decision-making process the whole time you spend cleaning data.</span>
<span id="cb47-8"><a href="#cb47-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-9"><a href="#cb47-9" aria-hidden="true" tabindex="-1"></a><span class="fu">## Cleaning Data Using dplyr</span></span>
<span id="cb47-10"><a href="#cb47-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-11"><a href="#cb47-11" aria-hidden="true" tabindex="-1"></a>As in the other sections of this book, we will be using the Tidyverse approach to data cleaning here. The primary Tidyverse package for data cleaning is <span class="co">[</span><span class="ot">dplyr</span><span class="co">](https://dplyr.tidyverse.org/)</span> and it contains most of the functions we will be using in this chapter.</span>
<span id="cb47-12"><a href="#cb47-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-13"><a href="#cb47-13" aria-hidden="true" tabindex="-1"></a>Rather than downloading a .csv file and using the <span class="in">`read_csv()`</span> function to load in our data for this chapter, we will be using a package which contains multiple data sets. The data come from the <span class="co">[</span><span class="ot">United Nations General Assembly</span><span class="co">](https://github.com/dgrtwo/unvotes)</span>. First install the unvotes package by running the following command in your Console.</span>
<span id="cb47-14"><a href="#cb47-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-15"><a href="#cb47-15" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, eval=FALSE}</span></span>
<span id="cb47-16"><a href="#cb47-16" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"unvotes"</span>)</span>
<span id="cb47-17"><a href="#cb47-17" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-18"><a href="#cb47-18" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-19"><a href="#cb47-19" aria-hidden="true" tabindex="-1"></a>Then run</span>
<span id="cb47-20"><a href="#cb47-20" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-21"><a href="#cb47-21" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, message=FALSE, warning=FALSE}</span></span>
<span id="cb47-22"><a href="#cb47-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(unvotes)</span>
<span id="cb47-23"><a href="#cb47-23" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb47-24"><a href="#cb47-24" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-25"><a href="#cb47-25" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-26"><a href="#cb47-26" aria-hidden="true" tabindex="-1"></a>When you use the <span class="in">`library()`</span> function, many packages automatically load small data sets which immediately become available for use. However, accessing these data can be a bit confusing because they do not automatically show up as objects in your Environment tab. Let's add the unvotes data sets to our Environment with the following chunk of code:</span>
<span id="cb47-27"><a href="#cb47-27" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-30"><a href="#cb47-30" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-31"><a href="#cb47-31" aria-hidden="true" tabindex="-1"></a>un_votes <span class="ot">&lt;-</span> un_votes</span>
<span id="cb47-32"><a href="#cb47-32" aria-hidden="true" tabindex="-1"></a>un_roll_calls <span class="ot">&lt;-</span> un_roll_calls</span>
<span id="cb47-33"><a href="#cb47-33" aria-hidden="true" tabindex="-1"></a>un_roll_call_issues <span class="ot">&lt;-</span> un_roll_call_issues</span>
<span id="cb47-34"><a href="#cb47-34" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-35"><a href="#cb47-35" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-36"><a href="#cb47-36" aria-hidden="true" tabindex="-1"></a>About the data</span>
<span id="cb47-37"><a href="#cb47-37" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-38"><a href="#cb47-38" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`un_votes`</span>, country-vote level data. Each row is a country's vote on a particular UN Assembly resolution.</span>
<span id="cb47-39"><a href="#cb47-39" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`un_roll_calls`</span>, resolution level data. Contains information about each resolution.</span>
<span id="cb47-40"><a href="#cb47-40" aria-hidden="true" tabindex="-1"></a><span class="ss">-   </span><span class="in">`un_roll_call_issues`</span>, resolution level data. Contains the issue-area for each resolution.</span>
<span id="cb47-41"><a href="#cb47-41" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-42"><a href="#cb47-42" aria-hidden="true" tabindex="-1"></a><span class="fu">### The Pipe Operator {.unnumbered}</span></span>
<span id="cb47-43"><a href="#cb47-43" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-44"><a href="#cb47-44" aria-hidden="true" tabindex="-1"></a>Before we get started using dplyr we need to first introduce the "pipe" operator <span class="in">`|&gt;`</span>. Pipes are an extremely convenient tool for linking several functions together. They work by passing the object on the left hand side of the pipe into the function following the pipe. <span class="co">[</span><span class="ot">Here is an example</span><span class="co">](https://twitter.com/andrewheiss/status/1359583543509348356)</span>.</span>
<span id="cb47-45"><a href="#cb47-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-46"><a href="#cb47-46" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, eval=FALSE}</span></span>
<span id="cb47-47"><a href="#cb47-47" aria-hidden="true" tabindex="-1"></a><span class="co"># The pipe way</span></span>
<span id="cb47-48"><a href="#cb47-48" aria-hidden="true" tabindex="-1"></a>me <span class="sc">|&gt;</span> </span>
<span id="cb47-49"><a href="#cb47-49" aria-hidden="true" tabindex="-1"></a>  <span class="fu">wake_up</span>(<span class="at">time =</span> <span class="st">"8:00"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb47-50"><a href="#cb47-50" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_out_of_bed</span>(<span class="at">side =</span> <span class="st">"correct"</span>) <span class="sc">|&gt;</span> </span>
<span id="cb47-51"><a href="#cb47-51" aria-hidden="true" tabindex="-1"></a>  <span class="fu">get_dressed</span>(<span class="at">pants =</span> <span class="cn">TRUE</span>, <span class="at">shirt =</span> <span class="cn">TRUE</span>) <span class="sc">|&gt;</span> </span>
<span id="cb47-52"><a href="#cb47-52" aria-hidden="true" tabindex="-1"></a>  <span class="fu">leave_house</span>(<span class="at">car =</span> <span class="cn">FALSE</span>, <span class="at">bike =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-53"><a href="#cb47-53" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-54"><a href="#cb47-54" aria-hidden="true" tabindex="-1"></a><span class="co"># The non-pipe way</span></span>
<span id="cb47-55"><a href="#cb47-55" aria-hidden="true" tabindex="-1"></a><span class="fu">leave_house</span>(<span class="fu">get_dressed</span>(<span class="fu">get_out_of_bed</span>(<span class="fu">wake_up</span>(me, <span class="at">time =</span> <span class="st">"8:00"</span>), <span class="at">side =</span> <span class="st">"correct"</span>), <span class="at">pants =</span> <span class="cn">TRUE</span>, <span class="at">shirt =</span> <span class="cn">TRUE</span>), <span class="at">car =</span> <span class="cn">FALSE</span>, <span class="at">bike =</span> <span class="cn">TRUE</span>)</span>
<span id="cb47-56"><a href="#cb47-56" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-57"><a href="#cb47-57" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-58"><a href="#cb47-58" aria-hidden="true" tabindex="-1"></a>Both code chunks above will end up doing the same thing. But the pipe method is much easier to write, and much easier for others to read and understand. </span>
<span id="cb47-59"><a href="#cb47-59" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-60"><a href="#cb47-60" aria-hidden="true" tabindex="-1"></a>Before R version 4.1, the pipe operator was only available in the <span class="co">[</span><span class="ot">magrittr</span><span class="co">](https://magrittr.tidyverse.org/)</span> package (which remains part of the Tidyverse). The magrittr pipe is written <span class="in">`%&gt;%`</span> and many R users continue to use this over the native R <span class="in">`|&gt;`</span>. There are a few very minor differences between the two pipes, which you should feel free to ignore. We use the native R <span class="in">`|&gt;`</span> pipe in this book because it is generally a good idea, all else equal, to reduce your dependency on outside packages when writing code. </span>
<span id="cb47-61"><a href="#cb47-61" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-62"><a href="#cb47-62" aria-hidden="true" tabindex="-1"></a><span class="fu">## Working with Columns</span></span>
<span id="cb47-63"><a href="#cb47-63" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-64"><a href="#cb47-64" aria-hidden="true" tabindex="-1"></a>Each column in a data set typically represents a single variable, or attribute, relating to the observation in a particular row. In this section we will look at some of dplyr's functions for working with columns.</span>
<span id="cb47-65"><a href="#cb47-65" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-66"><a href="#cb47-66" aria-hidden="true" tabindex="-1"></a><span class="fu">### Select {.unnumbered}</span></span>
<span id="cb47-67"><a href="#cb47-67" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-68"><a href="#cb47-68" aria-hidden="true" tabindex="-1"></a>The <span class="in">`select()`</span> function is primarily used to remove unwanted columns from the data. Here is an example.</span>
<span id="cb47-69"><a href="#cb47-69" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-72"><a href="#cb47-72" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-73"><a href="#cb47-73" aria-hidden="true" tabindex="-1"></a>un_roll_calls <span class="sc">|&gt;</span> </span>
<span id="cb47-74"><a href="#cb47-74" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(rcid, date) <span class="co"># Keeping only two variables</span></span>
<span id="cb47-75"><a href="#cb47-75" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-76"><a href="#cb47-76" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-77"><a href="#cb47-77" aria-hidden="true" tabindex="-1"></a>Note that the code chunk above did not alter the data set object <span class="in">`un_roll_calls`</span>. If we wanted to take this smaller data set and use it for something else, we will need to use the assignment operator <span class="in">`&lt;-`</span> to save our work.</span>
<span id="cb47-78"><a href="#cb47-78" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-81"><a href="#cb47-81" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-82"><a href="#cb47-82" aria-hidden="true" tabindex="-1"></a><span class="co"># This creates a new object called "small_un_roll_calls"</span></span>
<span id="cb47-83"><a href="#cb47-83" aria-hidden="true" tabindex="-1"></a><span class="co"># containing only rcid and date columns</span></span>
<span id="cb47-84"><a href="#cb47-84" aria-hidden="true" tabindex="-1"></a>small_un_roll_calls <span class="ot">&lt;-</span> un_roll_calls <span class="sc">|&gt;</span> </span>
<span id="cb47-85"><a href="#cb47-85" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(rcid, date)</span>
<span id="cb47-86"><a href="#cb47-86" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-87"><a href="#cb47-87" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-88"><a href="#cb47-88" aria-hidden="true" tabindex="-1"></a>The <span class="in">`select()`</span> function can be very versatile. Rather than typing every column name we want to keep, it is often faster to specify the columns we want to drop.</span>
<span id="cb47-89"><a href="#cb47-89" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-92"><a href="#cb47-92" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-93"><a href="#cb47-93" aria-hidden="true" tabindex="-1"></a>un_roll_calls <span class="sc">|&gt;</span> </span>
<span id="cb47-94"><a href="#cb47-94" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="sc">-</span>session) <span class="co"># Keep everything except session column</span></span>
<span id="cb47-95"><a href="#cb47-95" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-96"><a href="#cb47-96" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-97"><a href="#cb47-97" aria-hidden="true" tabindex="-1"></a>There are many other convenient ways to selection columns (e.g. by common names, by type of data, or by position in the data set). For a full list of ways to use <span class="in">`select()`</span> see <span class="co">[</span><span class="ot">this link</span><span class="co">](https://dplyr.tidyverse.org/reference/select.html)</span>. Here is one example of selecting every column which is a "character" type.</span>
<span id="cb47-98"><a href="#cb47-98" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-101"><a href="#cb47-101" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-102"><a href="#cb47-102" aria-hidden="true" tabindex="-1"></a>un_roll_calls <span class="sc">|&gt;</span> </span>
<span id="cb47-103"><a href="#cb47-103" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="fu">where</span>(is.character))</span>
<span id="cb47-104"><a href="#cb47-104" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-105"><a href="#cb47-105" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-106"><a href="#cb47-106" aria-hidden="true" tabindex="-1"></a>Lastly, we can use <span class="in">`select()`</span> to rename columns in our data. The chunk of code below selects the "unres" and date columns, and renames "unres" to "un_resolution" at the same time.</span>
<span id="cb47-107"><a href="#cb47-107" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-110"><a href="#cb47-110" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-111"><a href="#cb47-111" aria-hidden="true" tabindex="-1"></a>un_roll_calls <span class="sc">|&gt;</span> </span>
<span id="cb47-112"><a href="#cb47-112" aria-hidden="true" tabindex="-1"></a>  <span class="fu">select</span>(<span class="at">un_resolution =</span> unres, date)</span>
<span id="cb47-113"><a href="#cb47-113" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-114"><a href="#cb47-114" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-115"><a href="#cb47-115" aria-hidden="true" tabindex="-1"></a>If you only want to rename columns---without specifying which to select---dplyr has a function <span class="in">`rename()`</span> for this purpose. The syntax is similar to the code chunk above <span class="in">`new_variable_name = original_variable_name`</span>. This code will keep all columns and change the names of the specified variables.</span>
<span id="cb47-116"><a href="#cb47-116" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-119"><a href="#cb47-119" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-120"><a href="#cb47-120" aria-hidden="true" tabindex="-1"></a>un_roll_calls <span class="sc">|&gt;</span> </span>
<span id="cb47-121"><a href="#cb47-121" aria-hidden="true" tabindex="-1"></a>  <span class="fu">rename</span>(<span class="at">un_resolution =</span> unres,</span>
<span id="cb47-122"><a href="#cb47-122" aria-hidden="true" tabindex="-1"></a>         <span class="at">amendment =</span> amend,</span>
<span id="cb47-123"><a href="#cb47-123" aria-hidden="true" tabindex="-1"></a>         <span class="at">paragraph =</span> para)</span>
<span id="cb47-124"><a href="#cb47-124" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-125"><a href="#cb47-125" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-126"><a href="#cb47-126" aria-hidden="true" tabindex="-1"></a><span class="fu">### Mutate {.unnumbered}</span></span>
<span id="cb47-127"><a href="#cb47-127" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-128"><a href="#cb47-128" aria-hidden="true" tabindex="-1"></a>The <span class="in">`select()`</span> and <span class="in">`rename()`</span> functions are great for tidying up your data sets, but they do not change the underlying variables. To change existing variables or to create new ones we use <span class="in">`mutate()`</span>.</span>
<span id="cb47-129"><a href="#cb47-129" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-130"><a href="#cb47-130" aria-hidden="true" tabindex="-1"></a>Let's say we discovered that all the roll call IDs in the column "rcid" were supposed to be in multiples of 10. The code chunk below creates a new variable called "rcid_10" which is simply the value of the original "rcid" variable multiplied by 10.</span>
<span id="cb47-131"><a href="#cb47-131" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-134"><a href="#cb47-134" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-135"><a href="#cb47-135" aria-hidden="true" tabindex="-1"></a>un_votes <span class="sc">|&gt;</span> </span>
<span id="cb47-136"><a href="#cb47-136" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rcid_10 =</span> rcid <span class="sc">*</span> <span class="dv">10</span>) <span class="co"># Creates the new rcid_10 variable</span></span>
<span id="cb47-137"><a href="#cb47-137" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-138"><a href="#cb47-138" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-139"><a href="#cb47-139" aria-hidden="true" tabindex="-1"></a>If you didn't want to create a brand new variable, but instead wanted to overwrite the original variable, you just need to put the original variable to the left of the <span class="in">`=`</span> in <span class="in">`mutate()`</span>.</span>
<span id="cb47-140"><a href="#cb47-140" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-143"><a href="#cb47-143" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-144"><a href="#cb47-144" aria-hidden="true" tabindex="-1"></a>un_votes <span class="sc">|&gt;</span> </span>
<span id="cb47-145"><a href="#cb47-145" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rcid =</span> rcid <span class="sc">*</span> <span class="dv">10</span>) <span class="co"># Overwrites the existing rcid variable</span></span>
<span id="cb47-146"><a href="#cb47-146" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-147"><a href="#cb47-147" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-148"><a href="#cb47-148" aria-hidden="true" tabindex="-1"></a>We commonly need to create a new variable whose values depend on the values of one of the original variables. The function <span class="in">`case_when()`</span> helps us do this inside <span class="in">`mutate()`</span>.</span>
<span id="cb47-149"><a href="#cb47-149" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-152"><a href="#cb47-152" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-153"><a href="#cb47-153" aria-hidden="true" tabindex="-1"></a>un_votes <span class="sc">|&gt;</span> </span>
<span id="cb47-154"><a href="#cb47-154" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vote_dummy =</span> <span class="fu">case_when</span>(vote <span class="sc">==</span> <span class="st">"yes"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb47-155"><a href="#cb47-155" aria-hidden="true" tabindex="-1"></a>                                vote <span class="sc">==</span> <span class="st">"no"</span> <span class="sc">~</span> <span class="dv">0</span>))</span>
<span id="cb47-156"><a href="#cb47-156" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-157"><a href="#cb47-157" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-158"><a href="#cb47-158" aria-hidden="true" tabindex="-1"></a>As you can see, the code chunk above creates a new variable called "vote_dummy" which takes the value <span class="in">`1`</span> if "vote" equals <span class="in">`"yes"`</span> and takes the values <span class="in">`0`</span> if "vote" equals <span class="in">`"no"`</span>. Like other programming languages, R uses the <span class="in">`==`</span> logical operator to check whether a value *equals*, or is equivalent, to some other value. This is different from the single <span class="in">`=`</span> which is used to create entire new variables inside <span class="in">`mutate()`</span>. </span>
<span id="cb47-159"><a href="#cb47-159" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-160"><a href="#cb47-160" aria-hidden="true" tabindex="-1"></a>Here is one more example using <span class="in">`case_when()`</span>.</span>
<span id="cb47-161"><a href="#cb47-161" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-164"><a href="#cb47-164" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-165"><a href="#cb47-165" aria-hidden="true" tabindex="-1"></a>un_votes <span class="sc">|&gt;</span> </span>
<span id="cb47-166"><a href="#cb47-166" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">rcid_era =</span> <span class="fu">case_when</span>(rcid <span class="sc">&lt;</span> <span class="dv">2000</span> <span class="sc">~</span> <span class="st">"old"</span>,</span>
<span id="cb47-167"><a href="#cb47-167" aria-hidden="true" tabindex="-1"></a>                              rcid <span class="sc">&gt;=</span> <span class="dv">2000</span> <span class="sc">&amp;</span> rcid <span class="sc">&lt;</span> <span class="dv">6000</span> <span class="sc">~</span> <span class="st">"middle"</span>,</span>
<span id="cb47-168"><a href="#cb47-168" aria-hidden="true" tabindex="-1"></a>                              rcid <span class="sc">&gt;=</span> <span class="dv">6000</span> <span class="sc">~</span> <span class="st">"recent"</span>))</span>
<span id="cb47-169"><a href="#cb47-169" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-170"><a href="#cb47-170" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-171"><a href="#cb47-171" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-172"><a href="#cb47-172" aria-hidden="true" tabindex="-1"></a>The new variable "rcid_era" takes three values, <span class="in">`"old"`</span>, <span class="in">`"middle"`</span>, and <span class="in">`"recent"`</span> based on what range the "rcid" variable falls within.</span>
<span id="cb47-173"><a href="#cb47-173" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-174"><a href="#cb47-174" aria-hidden="true" tabindex="-1"></a>To recap, the most commonly used functions for cleaning columns/variables in your data are:</span>
<span id="cb47-175"><a href="#cb47-175" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-176"><a href="#cb47-176" aria-hidden="true" tabindex="-1"></a><span class="ss">  -   </span><span class="in">`select()`</span> removes and/or renames columns.</span>
<span id="cb47-177"><a href="#cb47-177" aria-hidden="true" tabindex="-1"></a><span class="ss">  -   </span><span class="in">`rename()`</span> renames existing columns without removing any.</span>
<span id="cb47-178"><a href="#cb47-178" aria-hidden="true" tabindex="-1"></a><span class="ss">  -   </span><span class="in">`mutate()`</span> changes the values of existing columns and creates new columns.</span>
<span id="cb47-179"><a href="#cb47-179" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-180"><a href="#cb47-180" aria-hidden="true" tabindex="-1"></a><span class="fu">## Working with Rows</span></span>
<span id="cb47-181"><a href="#cb47-181" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-182"><a href="#cb47-182" aria-hidden="true" tabindex="-1"></a><span class="fu">### Filter {.unnumbered}</span></span>
<span id="cb47-183"><a href="#cb47-183" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-184"><a href="#cb47-184" aria-hidden="true" tabindex="-1"></a>Dplyr's primary function for removing unwanted rows is <span class="in">`filter()`</span>. Like we saw when using <span class="in">`case_when()`</span> inside <span class="in">`mutate()`</span>, using <span class="in">`filter()`</span> requires some practice with logical operators. The function <span class="in">`filter()`</span> works by specifying some variable and only keeping rows in the data for which the logical operation evaluates to <span class="in">`TRUE`</span>. Here is an example.</span>
<span id="cb47-185"><a href="#cb47-185" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-188"><a href="#cb47-188" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-189"><a href="#cb47-189" aria-hidden="true" tabindex="-1"></a>un_roll_calls <span class="sc">|&gt;</span> </span>
<span id="cb47-190"><a href="#cb47-190" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(importantvote <span class="sc">==</span> <span class="dv">1</span>)</span>
<span id="cb47-191"><a href="#cb47-191" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-192"><a href="#cb47-192" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-193"><a href="#cb47-193" aria-hidden="true" tabindex="-1"></a>The original "un_roll_calls" data set object has 6202 rows, whereas this new data set only has 411 rows. This is because we filtered out any row in which the variable "importantvote" was not equal to <span class="in">`1`</span>. Like <span class="in">`select()`</span>, we can extend the use of <span class="in">`filter()`</span> in many ways.</span>
<span id="cb47-194"><a href="#cb47-194" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-197"><a href="#cb47-197" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-198"><a href="#cb47-198" aria-hidden="true" tabindex="-1"></a><span class="co"># &amp; for AND</span></span>
<span id="cb47-199"><a href="#cb47-199" aria-hidden="true" tabindex="-1"></a>un_roll_calls <span class="sc">|&gt;</span> </span>
<span id="cb47-200"><a href="#cb47-200" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(importantvote <span class="sc">==</span> <span class="dv">1</span> <span class="sc">&amp;</span> session <span class="sc">&gt;</span> <span class="dv">40</span>)</span>
<span id="cb47-201"><a href="#cb47-201" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-202"><a href="#cb47-202" aria-hidden="true" tabindex="-1"></a><span class="co"># | for OR</span></span>
<span id="cb47-203"><a href="#cb47-203" aria-hidden="true" tabindex="-1"></a>un_roll_calls <span class="sc">|&gt;</span> </span>
<span id="cb47-204"><a href="#cb47-204" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(importantvote <span class="sc">==</span> <span class="dv">1</span> <span class="sc">|</span> session <span class="sc">&gt;</span> <span class="dv">40</span>)</span>
<span id="cb47-205"><a href="#cb47-205" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-206"><a href="#cb47-206" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-207"><a href="#cb47-207" aria-hidden="true" tabindex="-1"></a>The first chunk above filters out all rows in which "importantvote" did not equal <span class="in">`1`</span> **AND** "session" was less than `40`. The second chunk above filters out all rows in which "importantvote" did not equal `1` **OR** "session" was less than <span class="in">`40`</span>.</span>
<span id="cb47-208"><a href="#cb47-208" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-209"><a href="#cb47-209" aria-hidden="true" tabindex="-1"></a>Removing missing, or <span class="in">`NA`</span>, values is another common job for <span class="in">`filter()`</span>. To do this you can use the function <span class="in">`is.na()`</span> inside <span class="in">`filter()`</span>. The function <span class="in">`is.na()`</span> evaluates to <span class="in">`TRUE`</span> if the variable's value is <span class="in">`NA`</span> and evaluates to <span class="in">`FALSE`</span> otherwise. Because <span class="in">`filter()`</span> only keeps rows where the condition evaluates to <span class="in">`TRUE`</span>, in order to *remove* <span class="in">`NA`</span> values we need to negate <span class="in">`is.na()`</span> with the <span class="in">`!`</span> operator. The <span class="in">`!`</span> operator flips the truthiness of any logical statement it precedes. </span>
<span id="cb47-210"><a href="#cb47-210" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-213"><a href="#cb47-213" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-214"><a href="#cb47-214" aria-hidden="true" tabindex="-1"></a>un_roll_calls <span class="sc">|&gt;</span> </span>
<span id="cb47-215"><a href="#cb47-215" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(<span class="sc">!</span><span class="fu">is.na</span>(amend)) <span class="co"># Removing rows with NA for the amend variable</span></span>
<span id="cb47-216"><a href="#cb47-216" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-217"><a href="#cb47-217" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-218"><a href="#cb47-218" aria-hidden="true" tabindex="-1"></a>It can be confusing to think in terms of logical statements, especially when negation is involved! But you will become more comfortable with <span class="in">`filter()`</span> the more you practice.</span>
<span id="cb47-219"><a href="#cb47-219" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-220"><a href="#cb47-220" aria-hidden="true" tabindex="-1"></a>Another handy logical operator is <span class="in">`%in%`</span>. This lets you specify several values at once when checking whether to keep rows in <span class="in">`filter()`</span>. </span>
<span id="cb47-221"><a href="#cb47-221" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-224"><a href="#cb47-224" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-225"><a href="#cb47-225" aria-hidden="true" tabindex="-1"></a><span class="co"># Cumbersome way</span></span>
<span id="cb47-226"><a href="#cb47-226" aria-hidden="true" tabindex="-1"></a>un_votes <span class="sc">|&gt;</span> </span>
<span id="cb47-227"><a href="#cb47-227" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">==</span> <span class="st">"Kenya"</span> <span class="sc">|</span></span>
<span id="cb47-228"><a href="#cb47-228" aria-hidden="true" tabindex="-1"></a>         country <span class="sc">==</span> <span class="st">"Grenada"</span> <span class="sc">|</span></span>
<span id="cb47-229"><a href="#cb47-229" aria-hidden="true" tabindex="-1"></a>         country <span class="sc">==</span> <span class="st">"Canada"</span> <span class="sc">|</span></span>
<span id="cb47-230"><a href="#cb47-230" aria-hidden="true" tabindex="-1"></a>         country <span class="sc">==</span> <span class="st">"Latvia"</span> <span class="sc">|</span></span>
<span id="cb47-231"><a href="#cb47-231" aria-hidden="true" tabindex="-1"></a>         country <span class="sc">==</span> <span class="st">"Yemen"</span> <span class="sc">|</span></span>
<span id="cb47-232"><a href="#cb47-232" aria-hidden="true" tabindex="-1"></a>         country <span class="sc">==</span> <span class="st">"Angola"</span>)</span>
<span id="cb47-233"><a href="#cb47-233" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-234"><a href="#cb47-234" aria-hidden="true" tabindex="-1"></a><span class="co"># Easier way</span></span>
<span id="cb47-235"><a href="#cb47-235" aria-hidden="true" tabindex="-1"></a>country_list <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="st">"Kenya"</span>, <span class="st">"Grenada"</span>, <span class="st">"Canada"</span>,</span>
<span id="cb47-236"><a href="#cb47-236" aria-hidden="true" tabindex="-1"></a>                  <span class="st">"Latvia"</span>, <span class="st">"Yemen"</span>, <span class="st">"Angola"</span>)</span>
<span id="cb47-237"><a href="#cb47-237" aria-hidden="true" tabindex="-1"></a>un_votes <span class="sc">|&gt;</span> </span>
<span id="cb47-238"><a href="#cb47-238" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(country <span class="sc">%in%</span> country_list)</span>
<span id="cb47-239"><a href="#cb47-239" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-240"><a href="#cb47-240" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-241"><a href="#cb47-241" aria-hidden="true" tabindex="-1"></a>The two chunks of code above will produce the same filtered data set, but the second chunk requires fewer lines of code and is more flexible if we want to add or remove countries.</span>
<span id="cb47-242"><a href="#cb47-242" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-243"><a href="#cb47-243" aria-hidden="true" tabindex="-1"></a><span class="fu">### Aggregation {.unnumbered}</span></span>
<span id="cb47-244"><a href="#cb47-244" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-245"><a href="#cb47-245" aria-hidden="true" tabindex="-1"></a>Filtering is great for removing unwanted rows in your data. However, after using <span class="in">`filter()`</span> the data set's unit of analysis typically remains the same. In the code chunk above, for example, we removed most of the countries from our data, but each row in the resulting data set is still a unique country-vote observation. </span>
<span id="cb47-246"><a href="#cb47-246" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-247"><a href="#cb47-247" aria-hidden="true" tabindex="-1"></a>Let's say we want to reduce the data set down to the country level, rather than country-vote level, and examine the proportion of "no" votes taken by each country. We can do this in dplyr using the pair of functions <span class="in">`group_by()`</span> and <span class="in">`summarize()`</span>. Here is an example.</span>
<span id="cb47-248"><a href="#cb47-248" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-251"><a href="#cb47-251" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-252"><a href="#cb47-252" aria-hidden="true" tabindex="-1"></a>un_votes <span class="sc">|&gt;</span> </span>
<span id="cb47-253"><a href="#cb47-253" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Creating a new numeric dummy vote variable</span></span>
<span id="cb47-254"><a href="#cb47-254" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vote_dummy =</span> <span class="fu">case_when</span>(vote <span class="sc">==</span> <span class="st">"yes"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb47-255"><a href="#cb47-255" aria-hidden="true" tabindex="-1"></a>                                vote <span class="sc">==</span> <span class="st">"no"</span> <span class="sc">~</span> <span class="dv">0</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb47-256"><a href="#cb47-256" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Specify level of aggregation</span></span>
<span id="cb47-257"><a href="#cb47-257" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country) <span class="sc">|&gt;</span> </span>
<span id="cb47-258"><a href="#cb47-258" aria-hidden="true" tabindex="-1"></a>  <span class="co"># Perform the aggregation function by group</span></span>
<span id="cb47-259"><a href="#cb47-259" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">proportion_yes_vote =</span> <span class="fu">mean</span>(vote_dummy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="cb47-260"><a href="#cb47-260" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-261"><a href="#cb47-261" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-262"><a href="#cb47-262" aria-hidden="true" tabindex="-1"></a>The code above uses the function <span class="in">`mean()`</span> to calculate the average value of "vote_dummy" within each country. Because "vote_dummy" takes the values <span class="in">`1`</span> and <span class="in">`0`</span>, this average can be interpreted as a proportion of 1's, or "yes" votes. We need to add <span class="in">`na.rm = TRUE`</span> inside <span class="in">`mean()`</span> to tell R to ignore <span class="in">`NA`</span> values when calculating this average.</span>
<span id="cb47-263"><a href="#cb47-263" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-264"><a href="#cb47-264" aria-hidden="true" tabindex="-1"></a>If we want to sort our data by the new aggregated column, we can do so using <span class="in">`arrange()`</span> after <span class="in">`summarize()`</span>.</span>
<span id="cb47-265"><a href="#cb47-265" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-268"><a href="#cb47-268" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-269"><a href="#cb47-269" aria-hidden="true" tabindex="-1"></a>un_votes <span class="sc">|&gt;</span> </span>
<span id="cb47-270"><a href="#cb47-270" aria-hidden="true" tabindex="-1"></a>  <span class="fu">mutate</span>(<span class="at">vote_dummy =</span> <span class="fu">case_when</span>(vote <span class="sc">==</span> <span class="st">"yes"</span> <span class="sc">~</span> <span class="dv">1</span>,</span>
<span id="cb47-271"><a href="#cb47-271" aria-hidden="true" tabindex="-1"></a>                                vote <span class="sc">==</span> <span class="st">"no"</span> <span class="sc">~</span> <span class="dv">0</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb47-272"><a href="#cb47-272" aria-hidden="true" tabindex="-1"></a>  <span class="fu">group_by</span>(country) <span class="sc">|&gt;</span> </span>
<span id="cb47-273"><a href="#cb47-273" aria-hidden="true" tabindex="-1"></a>  <span class="fu">summarize</span>(<span class="at">proportion_yes_vote =</span> <span class="fu">mean</span>(vote_dummy, <span class="at">na.rm =</span> <span class="cn">TRUE</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb47-274"><a href="#cb47-274" aria-hidden="true" tabindex="-1"></a>  <span class="fu">arrange</span>(proportion_yes_vote)</span>
<span id="cb47-275"><a href="#cb47-275" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-276"><a href="#cb47-276" aria-hidden="true" tabindex="-1"></a><span class="co"># Use arrange(desc(proportion_yes_vote))</span></span>
<span id="cb47-277"><a href="#cb47-277" aria-hidden="true" tabindex="-1"></a><span class="co"># to sort in descending order</span></span>
<span id="cb47-278"><a href="#cb47-278" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-279"><a href="#cb47-279" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-280"><a href="#cb47-280" aria-hidden="true" tabindex="-1"></a>The United States votes "No" at a much higher rate than other countries!</span>
<span id="cb47-281"><a href="#cb47-281" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-282"><a href="#cb47-282" aria-hidden="true" tabindex="-1"></a>Lastly, the dplyr function <span class="in">`count()`</span> is very handy for quickly tallying the number of observations within each category of a variable. Simply put the name of the variable you want to count inside <span class="in">`count()`</span> and voila.</span>
<span id="cb47-283"><a href="#cb47-283" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-286"><a href="#cb47-286" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-287"><a href="#cb47-287" aria-hidden="true" tabindex="-1"></a>un_roll_call_issues <span class="sc">|&gt;</span> </span>
<span id="cb47-288"><a href="#cb47-288" aria-hidden="true" tabindex="-1"></a>  <span class="fu">count</span>(issue)</span>
<span id="cb47-289"><a href="#cb47-289" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-290"><a href="#cb47-290" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-291"><a href="#cb47-291" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-292"><a href="#cb47-292" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-293"><a href="#cb47-293" aria-hidden="true" tabindex="-1"></a><span class="fu">## Merging Data</span></span>
<span id="cb47-294"><a href="#cb47-294" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-295"><a href="#cb47-295" aria-hidden="true" tabindex="-1"></a>So far we have only been working with one data set at a time. But it is rare to find all the data you need for a particular project in one single data set. Frequently we will have to merge data sets together in order to have all our variables in the same place. The most common way to merge data using dplyr is with the <span class="in">`left_join()`</span> function. </span>
<span id="cb47-296"><a href="#cb47-296" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-297"><a href="#cb47-297" aria-hidden="true" tabindex="-1"></a>To illustrate how <span class="in">`left_join()`</span> works, let's say we have two data sets: our main data set, <span class="in">`x`</span> and the data set we want to merge, <span class="in">`y`</span>. Here is an example:</span>
<span id="cb47-298"><a href="#cb47-298" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-299"><a href="#cb47-299" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, eval=FALSE}</span></span>
<span id="cb47-300"><a href="#cb47-300" aria-hidden="true" tabindex="-1"></a>xy_data <span class="ot">&lt;-</span> <span class="fu">left_join</span>(x, y, <span class="at">by =</span> <span class="st">"key_variable"</span>)</span>
<span id="cb47-301"><a href="#cb47-301" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-302"><a href="#cb47-302" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-303"><a href="#cb47-303" aria-hidden="true" tabindex="-1"></a>The new data set <span class="in">`xy_data`</span> is produced by merging the <span class="in">`y`</span> data set *into* the <span class="in">`x`</span> data set based on the shared value of the <span class="in">`key_variable`</span> variable. Left joins will always keep all rows in the <span class="in">`x`</span> data set, but will only merge in rows from <span class="in">`y`</span> if they match up with the <span class="in">`key_variable`</span>. Your key variable will typically be something like country ID code or a unit's name in the data. Because we like to use pipes in this course, the chunk of code above can be rewritten as:</span>
<span id="cb47-304"><a href="#cb47-304" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-305"><a href="#cb47-305" aria-hidden="true" tabindex="-1"></a><span class="in">```{r, eval=FALSE}</span></span>
<span id="cb47-306"><a href="#cb47-306" aria-hidden="true" tabindex="-1"></a>xy_data <span class="ot">&lt;-</span> x <span class="sc">|&gt;</span> </span>
<span id="cb47-307"><a href="#cb47-307" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(y, <span class="at">by =</span> <span class="st">"key_variable"</span>)</span>
<span id="cb47-308"><a href="#cb47-308" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-309"><a href="#cb47-309" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-310"><a href="#cb47-310" aria-hidden="true" tabindex="-1"></a>Now let's take a look at <span class="in">`left_join()`</span> using real data from the unvotes data set.</span>
<span id="cb47-311"><a href="#cb47-311" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-314"><a href="#cb47-314" aria-hidden="true" tabindex="-1"></a><span class="in">```{r}</span></span>
<span id="cb47-315"><a href="#cb47-315" aria-hidden="true" tabindex="-1"></a>un_votes <span class="sc">|&gt;</span> </span>
<span id="cb47-316"><a href="#cb47-316" aria-hidden="true" tabindex="-1"></a>  <span class="fu">left_join</span>(un_roll_calls, <span class="at">by =</span> <span class="st">"rcid"</span>)</span>
<span id="cb47-317"><a href="#cb47-317" aria-hidden="true" tabindex="-1"></a><span class="in">```</span></span>
<span id="cb47-318"><a href="#cb47-318" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-319"><a href="#cb47-319" aria-hidden="true" tabindex="-1"></a>The code chunk above merged all the variables from the <span class="in">`un_roll_calls`</span> data set into the <span class="in">`un_votes`</span> data set. Recall that the <span class="in">`un_votes`</span> data contains information about how countries voted on particular UN roll call votes, and the <span class="in">`un_roll_calls`</span> data contains information about the specific votes (such as whether the vote was an "importantvote"). If there were any rows in <span class="in">`un_roll_calls`</span> that had <span class="in">`rcid`</span> values which failed to match with an <span class="in">`rcid`</span> value in <span class="in">`un_votes`</span>, the row would not get merged.</span>
<span id="cb47-320"><a href="#cb47-320" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-321"><a href="#cb47-321" aria-hidden="true" tabindex="-1"></a>While <span class="in">`left_join()`</span> is far and away the most common, and useful, way to merge two data sets when using dplyr, there are various other types of merges which have their niche applications. For a more in-depth look at merging data in dplyr see <span class="co">[</span><span class="ot">this page</span><span class="co">](https://github.com/gadenbuie/tidyexplain)</span> with helpful animations.</span>
<span id="cb47-322"><a href="#cb47-322" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-323"><a href="#cb47-323" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- un_votes |&gt;  --&gt;</span></span>
<span id="cb47-324"><a href="#cb47-324" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--   left_join(un_roll_call_issues, by = "rcid") --&gt;</span></span>
<span id="cb47-325"><a href="#cb47-325" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-326"><a href="#cb47-326" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-327"><a href="#cb47-327" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-328"><a href="#cb47-328" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- un_roll_calls |&gt;  --&gt;</span></span>
<span id="cb47-329"><a href="#cb47-329" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--   left_join(un_roll_call_issues) --&gt;</span></span>
<span id="cb47-330"><a href="#cb47-330" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-331"><a href="#cb47-331" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-332"><a href="#cb47-332" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- ## Reshaping Data --&gt;</span></span>
<span id="cb47-333"><a href="#cb47-333" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-334"><a href="#cb47-334" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-335"><a href="#cb47-335" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- ```{r} --&gt;</span></span>
<span id="cb47-336"><a href="#cb47-336" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- wide_un_votes &lt;- un_votes |&gt;  --&gt;</span></span>
<span id="cb47-337"><a href="#cb47-337" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--   pivot_wider(id_cols = rcid, --&gt;</span></span>
<span id="cb47-338"><a href="#cb47-338" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--               values_from = vote, --&gt;</span></span>
<span id="cb47-339"><a href="#cb47-339" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--               names_from = country) --&gt;</span></span>
<span id="cb47-340"><a href="#cb47-340" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-341"><a href="#cb47-341" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- head(wide_un_votes) --&gt;</span></span>
<span id="cb47-342"><a href="#cb47-342" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- ``` --&gt;</span></span>
<span id="cb47-343"><a href="#cb47-343" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-344"><a href="#cb47-344" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- ```{r} --&gt;</span></span>
<span id="cb47-345"><a href="#cb47-345" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- long_un_votes &lt;- wide_un_votes |&gt;  --&gt;</span></span>
<span id="cb47-346"><a href="#cb47-346" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--   pivot_longer(cols = -rcid, --&gt;</span></span>
<span id="cb47-347"><a href="#cb47-347" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--                names_to = "country", --&gt;</span></span>
<span id="cb47-348"><a href="#cb47-348" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!--                values_to = "vote") --&gt;</span></span>
<span id="cb47-349"><a href="#cb47-349" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb47-350"><a href="#cb47-350" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- long_un_votes --&gt;</span></span>
<span id="cb47-351"><a href="#cb47-351" aria-hidden="true" tabindex="-1"></a><span class="co">&lt;!-- ``` --&gt;</span></span>
</code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div></div></div></div></div>
</div> <!-- /content -->



<script src="site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>