project:
  type: book

book:
  title: "UCSD Political Science Math Camp"
  repo-url: https://github.com/UCSDPoliMathCamp/MathCamp/
  repo-actions: [edit]
  favicon: favicon.ico
  reader-mode: true
  comments:
    hypothesis:
      theme: clean
  # downloads: [pdf]
  sidebar:
    title: "UCSD Political Science Math Camp"
    style: "docked"
    collapse-level: 2
    border: false
    search: true
  chapters:
    - index.Rmd
    - 00_warmup.Rmd
    - 01_prerequisites.Rmd
    - part: "I Introduction to R"
      chapters:
      - 11_orientation.Rmd
      - 12_visualization.Rmd
      - 13_data_wrangling_cleaning.Rmd
      - 14_loops_simulations.Rmd
      - 15_non-wysiwyg.Rmd
    - part: "II Linear Algebra"
      chapters:
      - 21_vector_matrix.Rmd
      - 22_linear_systems.Rmd
      - 23_matrix_inverse.Rmd
    - part: "III Calculus"
      chapters:
      - 31_limits.Rmd
      - 32_derivatives.Rmd
      - 33_optimization.Rmd
      - 34_intergrals.Rmd
    - part: "IV Probability"
      chapters:
      - 41_measuring_uncertainty.Rmd
      - 42_logic_probability.Rmd
      - 43_conditional.Rmd
      - 44_parameter_estimation.Rmd
      - 45_distributions.Rmd
    - 51_solutions-warmup.Rmd

format:
  html:
    theme:
      light: [cosmo, custom.scss]
    css: style.css
    fontsize: "16px"
    linestretch: 1.6
    mainfont: "Lora"
    monofont: "Fira Mono"
    html-math-method: katex
    smooth-scroll: true
    toc-title: "On this page"
    toc-depth: 4
    code-link: true
    code-overflow: wrap
    code-tools:
      toggle: true
    code-fold: false
    highlight-style: printing
    code-block-bg: true
  # see https://pandoc.org/MANUAL.html for all options
  # pdf:
  #   documentclass: scrbook
  #   lof: false
  #   lot: false
  #   toc: true
  #   fontfamily: libertinus
  #   fontfamilyoptions:
  #     - p
  #   monofont: inconsolata
  #   # include-in-header: preamble.tex
  #   classoption: [onecolumn, enabledeprecatedfontcommands]
  #   geometry:
  #     - top=30mm
  #     - left=20mm
  #     - heightrounded
  #   hyperrefoptions:
  #     - linktoc=all
  #   colorlinks: true
  #   linkcolor: "blue"
  #   biblio-style: apalike
  #   keep-tex: true
    # cite-method: citeproc
    # cite-method: natbib
  # epub:
  #   toc: true

latex-auto-install: true

knitr:
  opts_chunk:
    cache: true
    cache.lazy: false
    R.options:
      knitr.graphics.auto_pdf: true

execute:
  freeze: auto