## About this Booklet {-}

This booklet is adapted from the [Harvard Gov Prefresher booklet](https://iqss.github.io/prefresher/), maintained by [Shiro Kuriwaki](https://www.shirokuriwaki.com). 
It will serve as as the text for the UCSD Math Camp, taught by Keng-Chi Chang and Xiaohan Wu, and we have reordered and adapted it to fit the structure of our course.
For information about the role of this math camp as an introduction to graduate school, you may be interested in ["The Math Prefresher and The Collective Future of Political Science Graduate Training"](https://gking.harvard.edu/prefresher), in PS: Political Science & Politics, by Gary King, Shiro Kuriwaki, and Yon Soo Park.

### Authors and Contributors {-}

For information about the authors of the Harvard Gov Prefresher booklet, see [here](https://iqss.github.io/prefresher/index.html#authors-and-contributors).  
We have also updated it to include some material from previous instructors of the class at UCSD, including Bertrand Wilden (2022), Rachel Schoner (2021), Luke Sanford (2019-2020), Kathryn Baragwanath (2019-2020), Brandon Merrell (2018), Inbok Rhee (2018).

### Contributing {-}

We transitioned the booklet into a bookdown [github repository](https://github.com/UCSDPoliMathCamp/MathCamp) in 2021. 
As we update this version, we appreciate any bug reports or fixes appreciated. 

All changes should be made in the `.Rmd` files in the project root. 
To contribute a change, please make a pull request and set the repository maintainer as the reviewer.
